### ISSUE TITLE
README doesn't communicate the project very well

### ISSUE THREAD

**Issue by thundergolfer** [tobegit3hub/miniflow#1]
Hey, 

Just read through this repo's `README` and I have little idea what this project is or does. It says it's "the minimal Implementation" of TF, but this isn't clear to me. From the examples `miniflow` looks just like `tensorflow` but with some methods renamed, so it probably isn't a TF wrapper library. 

Looking at the source code it becomes clearer that this is a barebones rewrite of Tensorflow. In this case I think more of the `README` should be devoted to pointing this out and not so much on code examples. 

Maybe details more about the implementation; it's structure, your learnings, and the project's gaps. 

-------

Nice work btw. I'll be checking back on this to learn more about TF.

**Comment by tobegit3hub** [comment]
Thanks for your advice. @thundergolfer 

I have updated the `README.md` and hope it solved your problem.

**Comment by thundergolfer** [comment]
Nice
