### ISSUE TITLE
miniflow only supports python 2 instead of python 3

### ISSUE THREAD

**Issue by shuren0806** [tobegit3hub/miniflow#2]
hi tobe,

today I experienced miniflow first time, I found the following issue:
>>> import miniflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\***\AppData\Local\Programs\Python\Python35\lib\site-packages\miniflow\__init__.py", line 37, in <module>
    import graph
ImportError: No module named 'graph'

'graph' module is located in miniflow directory, and miniflow\__init_.py simply uses 'import graph' to import graph.
if I do not first change directory to site-packages\miniflow or PYTHONPATH does not set to the  site-packages\miniflow, I will get the above issue.

use 'from miniflow import graph' or 'from . import graph' can solve the issue, that is, we can import miniflow from any directory or not set PYTHONPATH. 
we need to replace ALL similar 'import graph'.

After I can successfully import miniflow by first change to site-packages\miniflow, but dir(tf) show almost nothing.  seems all imports in __init__.py are NOT executed. 
>>> dir(tf)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

when I execute import tensorflow as tf, it can successfully import as expected. 
I think there are some jobs to be done to make it import easily as tensorflow.

note: I am not very familiar with python. maybe the issue is not an issue, or maybe you have good solution. anyway, I just create the issue for your notice.

**Comment by liudragonfly** [comment]
Use Python2 instead of Python3. Python2 Relative Imports. Python3 Absolute Imports.

**Comment by shuren0806** [comment]
as python3 is the mainstream. we should change it to absolute imports.
I just check the tensorflow code and find that it uses absolute imports and uses 'from __future__ import absolute_import'.

**Comment by shuren0806** [comment]
I just used python2 to try the example of miniflow, it can work!
so seems currently miniflow only supports python2.  we should explicitly state this in the README.md page.

**Comment by liudragonfly** [comment]
You are right. Using absolute imports is necessary. Hope @tobegit3hub change it.

**Comment by tobegit3hub** [comment]
Thanks @shuren0806 and @liudragonfly .

MiniFlow is only tested in Python 2.7 environment but the support of Python 3 is really necessary. I will test in Python 2 and 3 soon.

By the way, any issue and pull request for this are warmly welcome 😃

**Comment by tobegit3hub** [comment]
There is something to change for Python 3.

[x] `has_key()` in dictionary, replaced with `in`.
[x] `iteritems()` in dictionary, replaced with `items()`.
[x] `import graph`the relative path, replace with `from . import graph`
[x] `httplib` in webhdfs, remove from the package
[x] `urlparse` in webhdfs, remove from the package

**Comment by tobegit3hub** [comment]
This issue is fixed and you can test in python2 or python3 after upgrading `miniflow`.

```
pip install --upgrade 'miniflow>=0.2.8'
```

<img width="1111" alt="screen shot 2017-07-10 at 10 19 53 am" src="https://user-images.githubusercontent.com/2715000/28000672-d90dbf34-6559-11e7-9eb1-66b9a73d6c33.png">
