### ISSUE TITLE
doubts in grad function of DivideOp

### ISSUE THREAD

**Issue by npuichigo** [tobegit3hub/miniflow#3]
I found that in grad func of MultipleOp, op1 or op2 may be different types, so the implementation of grad func should take them into consideration. So why grad func of DivideOp just use:
```self._op1.grad(partial_derivative_opname) / self._op2.grad(partial_derivative_opname)```

**Comment by tobegit3hub** [comment]
Nice catch and there is something we need to implement in `DivideOp`. It should be a little complicated than `AddOp`.

**Comment by tobegit3hub** [comment]
It works now and here is the result of unit test. @npuichigo 

<img width="389" alt="screen shot 2017-07-15 at 5 13 09 pm" src="https://user-images.githubusercontent.com/2715000/28238199-2757ea86-6981-11e7-8fc2-b15505d54837.png">
