### ISSUE TITLE
Function get_variable needed

### ISSUE THREAD

**Issue by Kongsea** [tobegit3hub/miniflow#4]

**Comment by tobegit3hub** [comment]
Thanks @Kongsea . 

Do you mean the similar API like `tf.get_variable`? Or just get variables by names from the graph?

**Comment by Kongsea** [comment]
It's tf.get_variable().
Because we used this function in our graph definition.
Besides, functions like tf.contrib.layers.xavier_initializer and tf.losses.* are also missing. So is there a plan to implement them?
Thank you.

**Comment by tobegit3hub** [comment]
It is not that hard to implement `tf.get_variable` and we will add it soon.

Becoming completely compatible with `TensorFlow` would be great but we still need engineers to implement all that algorithms. Hope more developers can contribute for those.
